airtable_base: 
tables:
  manuscript_objects:
    csv: 
    airtable: 
    fields: fields/ms_objs.yml
  parts:
    csv: 
    airtable: 
    fields: fields/parts.yml
    index_col: ID
  layers:
    csv: 
    airtable: 
    fields: fields/layers.yml
  text_units:
    csv: 
    airtable: 
    fields: fields/text_units.yml
  work_witnesses:
    csv: 
    airtable: 
    fields: fields/work_witnesses.yml
    index_col: ID
  tocs:
    csv: 
    airtable: 
    fields: fields/tocs.yml
    index_col: ID
  excerpts:
    csv: 
    airtable: 
    fields: fields/excerpts.yml
    index_col: ID
  bibs:
    csv: 
    airtable: 
    fields: fields/bibs.yml
    index_col: ID
  paracontents:
    csv: 
    airtable: 
    fields: fields/paracontents.yml
    index_col: ID
  related_mss:
    csv: 
    airtable: 
    fields: fields/related_mss.yml
    index_col: ID
  writing:
    csv: 
    airtable:
    fields: fields/writing.yml
    index_col: ID
  # states:
  #   csv: 
  #   airtable: 
  #   fields: fields/states.yml
  # features:
  #   csv: 
  #   airtable: 
  #   fields: fields/features.yml
#  - supports:
#  - locations:
#  - scripts:
#  - writing_systems:
#  - languages:
#  - names: 
#  - places: 
#  - works: 
#  - genres: 
#  - contributors: 
#  - programs: 
