part_label:
  name: Part Label
  csv: text
  airtable: text
part_summary:
  name: Part Summary
  csv: text
  airtable: text
part_locus:
  name: Part Locus
  csv: text
  airtable: text
part_extent:
  name: Part Extent
  csv: text
  airtable: text
support_id:
  name: Support ID
  csv: text+
  airtable: text+
  delimiter: [","]
support_label:
  name: Support Label
  csv: text+
  airtable: record+
  delimiter: [","]
  lookup: supports
part_dim:
  name: Part Dimensions
  csv: text
  airtable: text
layer_ark:
  name: Layer ARK
  csv: text+
  airtable: record+
  delimiter: [","]
  lookup: layers
layer_type_id:
  name: Layer Type ID
  csv: text+
  airtable: text+
  delimiter: ["|~|"]
layer_type_label:
  name: Layer Type Label
  csv: text+
  airtable: text+
  delimiter: ["|~|"]
layer_label:
  name: Layer Label
  csv: text+
  airtable: text+
  delimiter: ["|~|"]
layer_locus:
  name: Layer Locus
  csv: text+
  airtable: text+
  delimiter: ["|~|"]
layer_level:
  name: Layer Level
  csv: text+
  airtable: text+
  delimiter: ["|~|"]
layer_sequence:
  name: Layer Sequence
  csv: text+
  airtable: text+
  delimiter: [","]
layer_sequence_override:
  name: Layer Sequence Override
  csv: text+
  airtable: text+
  delimiter: [","]
part_typed_notes:
  support:
    label: Support Note
    name: Support note
    csv: text+
    airtable: text+
    delimiter: ["|~|"]
  coll:
    label: Collation Note
    name: Part Collation note
    csv: text+
    airtable: text+
    delimiter: ["|~|"]
part_paracontent:
  name: Part Paracontents
  csv: record+
  airtable: record+
  delimiter: [","]
  lookup: paracontents.*
related_mss:
  name: Related Mss
  csv: record+
  airtable: record+
  delimiter: [","]
  lookup: related_mss.*